import Description from './Assets/Description.png';
import Abodely from './Assets/Abodely.png';
import AdminDashboard from './Assets/AdminDashboard.png';

export const projectList = [
  {
    title: 'Dashboard',
    description:
      'XYZ',
    image: AdminDashboard,
    alt: 'AdminDashboard landing page example',
    url: 'retail-admin-dashboard.netlify.app',
  },
  {
    title: 'Description Module',
    description:
      'ABC',
    image: Description,
    alt: 'Description example',
  },
  {
    title: 'Abodely Module',
    description:
      'ABC',
    image: Abodely,
    alt: 'Abodely example',
  },
  {
    title: 'Title',
    description:
      'ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF',
    image: Abodely,
    alt: 'Description example',
  },
  {
    title: 'Title',
    description:
      'ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ',
    image: Abodely,
    alt: 'Description example',
  },
  {
    title: 'Title',
    description:
      'ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ',
    image: Abodely,
    alt: 'Description example',
  },
  {
    title: 'Title',
    description:
      'ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ABCDASASFDSF ASDASDSAWR FSDVCDSCSDF ',
    image: Abodely,
    alt: 'Description example',
  },
  {
    title: 'Title',
    description:
      'ABC',
    image: Abodely,
    alt: 'Description example',
  },
];
